---
title: "Progress, challenges and opportunities for plant Red Listing"
author: "Steven Bachman"
date: "23 July 2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This repository contains code used in the paper: **"Progress, challenges and opportunities for plant Red Listing"**.  

All analysis was run in R aside from the workflow for Figure 1 (Microsoft powerpoint) and the map for Figure 3 (ArcMap 10.3).

See [Methods_description.md](/Methods_description.md) for detailed methods.


## Structure of this repository

| Item          | Description           |
| ------------- |-------------|
| .gitignore     | Description of this repository | 
| Methods.md   | Description of methods     | 
| README.md    | Files and directories to be ignored by git | 
| RedList_Challenges.Rproj    | RStudio project file     | 
| 01_data | Input data     | 
| 02_docs | Manuscript and associated docs     | 
| 03_figs | Figures generated by analysis     | 
| 04_outputs | Various outputs or intermediate  files     | 
| 05_R | Scripts with functions to execute analysis   | 

## License
To be determined

